# Generated by Django 4.1.4 on 2022-12-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-04-23'),
            preserve_default=False,
        ),
    ]
